---
- name: Debian | install current/latest network packages versions
  apt:
    pkg: '{{ interfaces_pkgs["debian"]  }}'
    state: '{{ interfaces_pkg_state }}'
    update_cache: yes
    cache_valid_time: 3600
  tags: package
  become: true

- name: Debian | install VLAN packages
  become: true
  apt:
    pkg: vlan
    state: '{{ interfaces_pkg_state }}'
    update_cache: yes
    cache_valid_time: 3600
  when: >
    all_interfaces |
    selectattr('device', 'match', vlan_interface_regex) |
    list |
    length > 0
  vars:
    all_interfaces: >
      {{ interfaces_ether_interfaces +
         interfaces_bridge_interfaces +
         interfaces_bond_interfaces }}
  notify:
    - Check whether /etc/modules-load.d exists
    - Make sure the 8021q module is loaded
    - Make sure the 8021q module is loaded at boot via /etc/modules-load.d
    - Make sure the 8021q module is loaded at boot via /etc/modules
  tags: package

- name: Debian | Copy new interfaces file to source interfaces.d
  become: true
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  tags: configuration
  when: not interfaces_merge

- name: Debian | Create the directory for interface cfg files
  become: true
  file:
    path: '{{ interfaces_net_path[ansible_facts.os_family|lower] }}'
    state: directory
  tags: configuration

- name: Debian | Ensure lo single configuration file
  copy:
    dest: /etc/network/interfaces.d/ifcfg-lo
    mode: 0644
    content: |
      # Loopback

      auto lo
      iface lo inet loopback
  when: interfaces_merge
