---
- name: Check active Ethernet interface state
  debug:
    msg: >
      Checking Ethernet interface configuration for {{ item.device }}:
      {{ ether_check }}
  with_items: "{{ interfaces_ether_interfaces }}"
  changed_when: ether_check.diff
  register: ether_check_result
  notify:
    - Bounce network devices
  vars:
    ether_check: "{{ item | ether_check }}"

- name: Create the network configuration file for ethernet devices
  become: true
  template:
    src: 'ethernet_{{ ansible_facts.os_family }}.j2'
    dest: '{{ interfaces_net_path[ansible_facts.os_family|lower] }}/ifcfg-{{ item.device }}'
  with_items: '{{ interfaces_ether_interfaces }}'
  register: ether_result
  notify:
    - Bounce network devices

- name: RedHat | Write configuration files for rhel route configuration
  become: true
  template:
    src: 'route_{{ ansible_facts.os_family }}.j2'
    dest: '{{ interfaces_net_path[ansible_facts.os_family|lower] }}/route-{{ item.device }}'
  with_items: '{{ interfaces_ether_interfaces }}'
  when:
    - item.route is defined
    - ansible_facts.os_family == 'RedHat'
  register: ether_route_add_result
  notify:
    - Bounce network devices

- name: RedHat | Write configuration files for rhel v6 route configuration
  become: true
  template:
    src: 'route6_{{ ansible_facts.os_family }}.j2'
    dest: '{{ interfaces_net_path[ansible_facts.os_family|lower] }}/route6-{{ item.device }}'
  with_items: '{{ interfaces_ether_interfaces }}'
  when:
    - item.ip6 is defined
    - item.ip6.route is defined
    - ansible_facts.os_family == 'RedHat'
  register: ether_route6_add_result
  notify:
    - Bounce network devices

- name: RedHat | Remove configuration files for rhel route configuration
  become: true
  file:
    path: '{{ interfaces_net_path[ansible_facts.os_family|lower] }}/route-{{ item.device }}'
    state: absent
  with_items: '{{ interfaces_ether_interfaces }}'
  when:
    - item.route is not defined
    - ansible_facts.os_family == 'RedHat'
  register: ether_route_del_result
  notify:
    - Bounce network devices

- name: RedHat | Remove configuration files for rhel v6 route configuration
  become: true
  file:
    path: '{{ interfaces_net_path[ansible_facts.os_family|lower] }}/route6-{{ item.device }}'
    state: absent
  with_items: '{{ interfaces_ether_interfaces }}'
  when:
    - item.ip6 is not defined
    - ansible_facts.os_family == 'RedHat'
  register: ether_route6_del_result
  notify:
    - Bounce network devices

- name: RedHat | Write configuration files for rhel rule configuration
  become: true
  template:
    src: 'rule_{{ ansible_facts.os_family }}.j2'
    dest: '{{ interfaces_net_path[ansible_facts.os_family|lower] }}/rule-{{ item.device }}'
  with_items: '{{ interfaces_ether_interfaces }}'
  when:
    - item.rules is defined
    - ansible_facts.os_family == 'RedHat'
  register: ether_rule_add_result
  notify:
    - Bounce network devices

- name: RedHat | Remove configuration files for rhel rule configuration
  become: true
  file:
    path: '{{ interfaces_net_path[ansible_facts.os_family|lower] }}/rule-{{ item.device }}'
    state: absent
  with_items: '{{ interfaces_ether_interfaces }}'
  when:
    - item.rules is not defined
    - ansible_facts.os_family == 'RedHat'
  register: ether_rule_del_result
  notify:
    - Bounce network devices

# ether_interfaces_changed is used in the 'Bounce network devices' handler.
- name: Set a fact containing changed ethernet devices
  vars:
    # Build a list of all Ethernet results.
    all_ether_results: >
      {{ ether_check_result.results | default([]) +
         ether_result.results | default([]) +
         ether_route_add_result.results | default([]) +
         ether_route_del_result.results | default([]) +
         ether_route6_add_result.results | default([]) +
         ether_route6_del_result.results | default([]) +
         ether_rule_add_result.results | default([]) +
         ether_rule_del_result.results | default([]) }}
    # Select those tasks which changed, and map to a list of the corresponding
    # Ethernet devices.
    ether_interfaces_changed: >
      {{ all_ether_results |
         select('changed') |
         map(attribute='item.device') |
         unique |
         list }}
    vlan_on_changed_interface_regex: "{{ '(' ~ ((ether_interfaces_changed + bond_master_interfaces_changed + bridge_interfaces_changed) | join('|')) ~ ')' ~ vlan_interface_suffix_regex }}"
    # Find VLAN interfaces which have a changed parent device. At least on
    # CentOS/RHEL 7 systems, any static routes on the VLAN interface are lost
    # if the parent goes down.
    vlans_on_changed_interfaces: >
      {{ all_ether_results |
         map(attribute='item.device') |
         select('match', vlan_on_changed_interface_regex) |
         unique |
         list }}
  set_fact:
    ether_interfaces_changed: "{{ (ether_interfaces_changed + vlans_on_changed_interfaces) | unique | list}}"
